//Список неподтвержденных платежей
GET http://localhost:8080/operator/payments/unapproved
Authorization: Basic admin admin
Accept: application/json

###

//Потдтверить платеж
PUT http://localhost:8080/operator/payments/approve/1
Authorization: Basic admin admin
Accept: application/json

###



//Активировать карту
PUT http://localhost:8080/operator/cards/approve/2
Authorization: Basic admin admin
Accept: application/json

###

//Список неактивированных карт
GET http://localhost:8080/operator/cards/unapproved
Authorization: Basic admin admin
Accept: application/json

###



//Добавление счета
POST http://localhost:8080/accounts
Content-Type: application/json

{
  "userId": 1
}

###

//Добавление физ лица
POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "Stas"
}

###

//Модуль 2

//Перевод средств контрагенту
POST http://localhost:8080/payments
Content-Type: application/json

{
  "amount": "200.20",
  "senderId": 1,
  "receiverId": 2
}

###

//Добавление контрагента
POST http://localhost:8080/users/counterparties
Content-Type: application/json

{
  "partyId": 2,
  "counterpartyId": 3
}

###

//Просмотр контрагентов
GET http://localhost:8080/users/1/counterparties
Accept: application/json

###

//Первый модуль

//Внесение средств
PUT http://localhost:8080/accounts
Content-Type: application/json

{
  "id": "1",
  "amount": "200"
}

###

//Проверка баланса
GET http://localhost:8080/accounts/1/balance
Accept: application/json


//Выпуск новой карты по счету
###
POST http://localhost:8080/cards/
Content-Type: application/json

{
  "accountId": 1
}

###

//Список карт по аккаунту
GET http://localhost:8080/cards/9
Accept: application/json


###
