POST http://localhost:8080/card
Content-Type: application/json

{
  "number": "LA TEST",
  "account_id": 1,
  "active": false
}

###
GET http://localhost:8080/card/test/54
Accept: application/json


###
